FROM golang:1.23.1-alpine AS builder

# Install build dependencies
RUN apk add --no-cache gcc musl-dev

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=1 GOOS=linux go build -o server cmd/server/main.go

FROM alpine:latest  
RUN apk --no-cache add ca-certificates

# Create log directory
RUN mkdir -p /var/log/app
WORKDIR /root/

COPY --from=builder /app/server .

EXPOSE 50051 8080
CMD ["./server"]