global:
  scrape_interval:     10s
  evaluation_interval: 10s


scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:9090']

  - job_name: 'movie-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['server:8080']
        labels:
          application: 'movie_grpc_service'

