// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: movie.proto

package movie_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Movie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Genre         string                 `protobuf:"bytes,3,opt,name=genre,proto3" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_movie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{0}
}

func (x *Movie) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

type CreateMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *Movie                 `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMovieRequest) Reset() {
	*x = CreateMovieRequest{}
	mi := &file_movie_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieRequest) ProtoMessage() {}

func (x *CreateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieRequest.ProtoReflect.Descriptor instead.
func (*CreateMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMovieRequest) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type CreateMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *Movie                 `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMovieResponse) Reset() {
	*x = CreateMovieResponse{}
	mi := &file_movie_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieResponse) ProtoMessage() {}

func (x *CreateMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieResponse.ProtoReflect.Descriptor instead.
func (*CreateMovieResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMovieResponse) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type ReadMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMovieRequest) Reset() {
	*x = ReadMovieRequest{}
	mi := &file_movie_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMovieRequest) ProtoMessage() {}

func (x *ReadMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMovieRequest.ProtoReflect.Descriptor instead.
func (*ReadMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{3}
}

func (x *ReadMovieRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *Movie                 `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMovieResponse) Reset() {
	*x = ReadMovieResponse{}
	mi := &file_movie_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMovieResponse) ProtoMessage() {}

func (x *ReadMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMovieResponse.ProtoReflect.Descriptor instead.
func (*ReadMovieResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{4}
}

func (x *ReadMovieResponse) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type ReadMoviesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMoviesRequest) Reset() {
	*x = ReadMoviesRequest{}
	mi := &file_movie_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMoviesRequest) ProtoMessage() {}

func (x *ReadMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMoviesRequest.ProtoReflect.Descriptor instead.
func (*ReadMoviesRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{5}
}

func (x *ReadMoviesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ReadMoviesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ReadMoviesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ReadMoviesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movie               `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	TotalRecords  int64                  `protobuf:"varint,2,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMoviesResponse) Reset() {
	*x = ReadMoviesResponse{}
	mi := &file_movie_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMoviesResponse) ProtoMessage() {}

func (x *ReadMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMoviesResponse.ProtoReflect.Descriptor instead.
func (*ReadMoviesResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{6}
}

func (x *ReadMoviesResponse) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

func (x *ReadMoviesResponse) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

type UpdateMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *Movie                 `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMovieRequest) Reset() {
	*x = UpdateMovieRequest{}
	mi := &file_movie_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieRequest) ProtoMessage() {}

func (x *UpdateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieRequest.ProtoReflect.Descriptor instead.
func (*UpdateMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMovieRequest) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type UpdateMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *Movie                 `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMovieResponse) Reset() {
	*x = UpdateMovieResponse{}
	mi := &file_movie_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieResponse) ProtoMessage() {}

func (x *UpdateMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieResponse.ProtoReflect.Descriptor instead.
func (*UpdateMovieResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMovieResponse) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type DeleteMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMovieRequest) Reset() {
	*x = DeleteMovieRequest{}
	mi := &file_movie_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieRequest) ProtoMessage() {}

func (x *DeleteMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieRequest.ProtoReflect.Descriptor instead.
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMovieRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMovieResponse) Reset() {
	*x = DeleteMovieResponse{}
	mi := &file_movie_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieResponse) ProtoMessage() {}

func (x *DeleteMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieResponse.ProtoReflect.Descriptor instead.
func (*DeleteMovieResponse) Descriptor() ([]byte, []int) {
	return file_movie_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMovieResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_movie_proto protoreflect.FileDescriptor

const file_movie_proto_rawDesc = "" +
	"\n" +
	"\vmovie.proto\x12\x05proto\"C\n" +
	"\x05Movie\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05genre\x18\x03 \x01(\tR\x05genre\"8\n" +
	"\x12CreateMovieRequest\x12\"\n" +
	"\x05movie\x18\x01 \x01(\v2\f.proto.MovieR\x05movie\"9\n" +
	"\x13CreateMovieResponse\x12\"\n" +
	"\x05movie\x18\x01 \x01(\v2\f.proto.MovieR\x05movie\"\"\n" +
	"\x10ReadMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x11ReadMovieResponse\x12\"\n" +
	"\x05movie\x18\x01 \x01(\v2\f.proto.MovieR\x05movie\"\\\n" +
	"\x11ReadMoviesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"_\n" +
	"\x12ReadMoviesResponse\x12$\n" +
	"\x06movies\x18\x01 \x03(\v2\f.proto.MovieR\x06movies\x12#\n" +
	"\rtotal_records\x18\x02 \x01(\x03R\ftotalRecords\"8\n" +
	"\x12UpdateMovieRequest\x12\"\n" +
	"\x05movie\x18\x01 \x01(\v2\f.proto.MovieR\x05movie\"9\n" +
	"\x13UpdateMovieResponse\x12\"\n" +
	"\x05movie\x18\x01 \x01(\v2\f.proto.MovieR\x05movie\"$\n" +
	"\x12DeleteMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteMovieResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xeb\x02\n" +
	"\fMovieService\x12F\n" +
	"\vCreateMovie\x12\x19.proto.CreateMovieRequest\x1a\x1a.proto.CreateMovieResponse\"\x00\x12?\n" +
	"\bGetMovie\x12\x17.proto.ReadMovieRequest\x1a\x18.proto.ReadMovieResponse\"\x00\x12B\n" +
	"\tGetMovies\x12\x18.proto.ReadMoviesRequest\x1a\x19.proto.ReadMoviesResponse\"\x00\x12F\n" +
	"\vUpdateMovie\x12\x19.proto.UpdateMovieRequest\x1a\x1a.proto.UpdateMovieResponse\"\x00\x12F\n" +
	"\vDeleteMovie\x12\x19.proto.DeleteMovieRequest\x1a\x1a.proto.DeleteMovieResponse\"\x00B'Z%github.com/renaldyhidayatt/movie_grpcb\x06proto3"

var (
	file_movie_proto_rawDescOnce sync.Once
	file_movie_proto_rawDescData []byte
)

func file_movie_proto_rawDescGZIP() []byte {
	file_movie_proto_rawDescOnce.Do(func() {
		file_movie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_movie_proto_rawDesc), len(file_movie_proto_rawDesc)))
	})
	return file_movie_proto_rawDescData
}

var file_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_movie_proto_goTypes = []any{
	(*Movie)(nil),               // 0: proto.Movie
	(*CreateMovieRequest)(nil),  // 1: proto.CreateMovieRequest
	(*CreateMovieResponse)(nil), // 2: proto.CreateMovieResponse
	(*ReadMovieRequest)(nil),    // 3: proto.ReadMovieRequest
	(*ReadMovieResponse)(nil),   // 4: proto.ReadMovieResponse
	(*ReadMoviesRequest)(nil),   // 5: proto.ReadMoviesRequest
	(*ReadMoviesResponse)(nil),  // 6: proto.ReadMoviesResponse
	(*UpdateMovieRequest)(nil),  // 7: proto.UpdateMovieRequest
	(*UpdateMovieResponse)(nil), // 8: proto.UpdateMovieResponse
	(*DeleteMovieRequest)(nil),  // 9: proto.DeleteMovieRequest
	(*DeleteMovieResponse)(nil), // 10: proto.DeleteMovieResponse
}
var file_movie_proto_depIdxs = []int32{
	0,  // 0: proto.CreateMovieRequest.movie:type_name -> proto.Movie
	0,  // 1: proto.CreateMovieResponse.movie:type_name -> proto.Movie
	0,  // 2: proto.ReadMovieResponse.movie:type_name -> proto.Movie
	0,  // 3: proto.ReadMoviesResponse.movies:type_name -> proto.Movie
	0,  // 4: proto.UpdateMovieRequest.movie:type_name -> proto.Movie
	0,  // 5: proto.UpdateMovieResponse.movie:type_name -> proto.Movie
	1,  // 6: proto.MovieService.CreateMovie:input_type -> proto.CreateMovieRequest
	3,  // 7: proto.MovieService.GetMovie:input_type -> proto.ReadMovieRequest
	5,  // 8: proto.MovieService.GetMovies:input_type -> proto.ReadMoviesRequest
	7,  // 9: proto.MovieService.UpdateMovie:input_type -> proto.UpdateMovieRequest
	9,  // 10: proto.MovieService.DeleteMovie:input_type -> proto.DeleteMovieRequest
	2,  // 11: proto.MovieService.CreateMovie:output_type -> proto.CreateMovieResponse
	4,  // 12: proto.MovieService.GetMovie:output_type -> proto.ReadMovieResponse
	6,  // 13: proto.MovieService.GetMovies:output_type -> proto.ReadMoviesResponse
	8,  // 14: proto.MovieService.UpdateMovie:output_type -> proto.UpdateMovieResponse
	10, // 15: proto.MovieService.DeleteMovie:output_type -> proto.DeleteMovieResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_movie_proto_init() }
func file_movie_proto_init() {
	if File_movie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_movie_proto_rawDesc), len(file_movie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_movie_proto_goTypes,
		DependencyIndexes: file_movie_proto_depIdxs,
		MessageInfos:      file_movie_proto_msgTypes,
	}.Build()
	File_movie_proto = out.File
	file_movie_proto_goTypes = nil
	file_movie_proto_depIdxs = nil
}
