{
 "title": "Movie",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Memory Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Heap Object",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(go_memstats_heap_objects[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(go_memstats_sys_bytes[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cpu usage seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Start Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(process_start_time_seconds[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}